#! /usr/bin/python

import pymongo
import os
import sys 

conn=pymongo.MongoClient()

odb=conn['config']
ndb=conn['jaguar']


equips=odb['equipment'].find({})
vlans=list(odb['vlans'].find({}))
vmap=dict(zip([x['_id'] for x in vlans],vlans))

for v in vlans:
	ndb['vlans'].remove({'_id': v['_id']})
	ndb['vlans'].insert(v)

for e in equips:
	e['vid']=vmap[e['vid']]
	ndb['equipment'].remove({'_id': e['_id']})
	ndb['equipment'].insert(e)
	
for a in odb['apps'].find({}):
	ndb['apps'].remove({'_id': a['_id']})
	ndb['apps'].insert(a)
	
for a in odb['switch'].find({}):
	ndb['switch'].remove({'_id': a['_id']})
	ndb['switch'].insert(a)
